let ERROR_RUNTIME = 'ERROR_RUNTIME';
let ERROR_SCRIPT = 'ERROR_SCRIPT';
let ERROR_STYLE = 'ERROR_STYLE';
let ERROR_IMAGE = 'ERROR_IMAGE';
let ERROR_AUDIO = 'ERROR_AUDIO';
let ERROR_VIDEO = 'ERROR_VIDEO';
let ERROR_CONSOLE = 'ERROR_CONSOLE';
let ERROR_TRY_CATHC = 'ERROR_TRY_CATHC';

export default[ERROR_RUNTIME, ERROR_SCRIPT, ERROR_STYLE, ERROR_IMAGE, ERROR_AUDIO, ERROR_VIDEO, ERROR_CONSOLE, ERROR_TRY_CATHC];
